//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruletka {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruletka.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejdřív musíš vsadit!.
        /// </summary>
        public static string BetError {
            get {
                return ResourceManager.GetString("BetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončit.
        /// </summary>
        public static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst hru.
        /// </summary>
        public static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snížit.
        /// </summary>
        public static string LowerBet {
            get {
                return ResourceManager.GetString("LowerBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová hra.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýšit.
        /// </summary>
        public static string RaiseBet {
            get {
                return ResourceManager.GetString("RaiseBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytočené číslo.
        /// </summary>
        public static string RolledNumber {
            get {
                return ResourceManager.GetString("RolledNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Točím se jako kolotoč!.
        /// </summary>
        public static string Spin {
            get {
                return ResourceManager.GetString("Spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cs.wikipedia.org/wiki/Ruleta.
        /// </summary>
        public static string TargetURL {
            get {
                return ResourceManager.GetString("TargetURL", resourceCulture);
            }
        }
    }
}
